CREATE TABLE [dbo].[CostosPptoProgSemanaLineaBase] (
    [referencia1]     VARCHAR (30)    NULL,
    [referencia2]     VARCHAR (30)    NULL,
    [referencia3]     VARCHAR (30)    NULL,
    [presupuesto]     VARCHAR (250)   NULL,
    [codcapi]         VARCHAR (10)    NULL,
    [capitulo]        VARCHAR (250)   NULL,
    [codunit]         VARCHAR (10)    NULL,
    [unitario]        VARCHAR (250)   NULL,
    [undunita]        VARCHAR (10)    NULL,
    [cantxppto]       DECIMAL (20, 2) NULL,
    [codinsu]         VARCHAR (10)    NULL,
    [insutipo]        VARCHAR (10)    NULL,
    [insumo]          VARCHAR (250)   NULL,
    [unidinsu]        VARCHAR (10)    NULL,
    [ctrlinven]       VARCHAR (6)     NULL,
    [validación]      VARCHAR (6)     NULL,
    [precioppto]      DECIMAL (20, 2) NULL,
    [consumounitario] DECIMAL (20, 3) NULL,
    [consumototal]    DECIMAL (20, 2) NULL,
    [adic]            DECIMAL (20, 2) NULL,
    [precioaut]       DECIMAL (20, 2) NULL,
    [preciocompra]    DECIMAL (20, 2) NULL,
    [precioentrado]   DECIMAL (20, 2) NULL,
    [ped]             DECIMAL (20, 2) NULL,
    [aprob]           DECIMAL (20, 2) NULL,
    [comp]            DECIMAL (20, 2) NULL,
    [ent]             DECIMAL (20, 2) NULL,
    [sali]            DECIMAL (20, 2) NULL,
    [traslado]        DECIMAL (20, 2) NULL,
    [xcomp]           DECIMAL (20, 2) NULL,
    [xent]            DECIMAL (20, 2) NULL,
    [saldoxunit]      DECIMAL (20, 2) NULL,
    [saldoxppto]      DECIMAL (20, 2) NULL,
    [vlrent]          DECIMAL (20, 2) NULL,
    [vlrenttraslado]  DECIMAL (20, 2) NULL,
    [vlrcompradoxent] DECIMAL (20, 2) NULL,
    [vlrxcomp]        DECIMAL (20, 2) NULL,
    [vlrtraslado]     DECIMAL (20, 2) NULL,
    [vlrproy]         DECIMAL (20, 2) NULL,
    [vlrproyejec]     DECIMAL (20, 2) NULL,
    [vlrini]          DECIMAL (20, 2) NULL,
    [vlrejec]         DECIMAL (20, 2) NULL,
    [IdFecha]         INT             NULL,
    [Clasificacion]   INT             NULL
);

