#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ArchivoCostos")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCostoEntrado(CostoEntrado instance);
    partial void UpdateCostoEntrado(CostoEntrado instance);
    partial void DeleteCostoEntrado(CostoEntrado instance);
    partial void InsertSalidas(Salidas instance);
    partial void UpdateSalidas(Salidas instance);
    partial void DeleteSalidas(Salidas instance);
    partial void InsertCostosPorFechas(CostosPorFechas instance);
    partial void UpdateCostosPorFechas(CostosPorFechas instance);
    partial void DeleteCostosPorFechas(CostosPorFechas instance);
    partial void InsertFechas(Fechas instance);
    partial void UpdateFechas(Fechas instance);
    partial void DeleteFechas(Fechas instance);
    partial void InsertOrdenes(Ordenes instance);
    partial void UpdateOrdenes(Ordenes instance);
    partial void DeleteOrdenes(Ordenes instance);
    partial void InsertPedidos(Pedidos instance);
    partial void UpdatePedidos(Pedidos instance);
    partial void DeletePedidos(Pedidos instance);
    #endregion
		
		public DataDataContext() : 
				base(global::Bll.Properties.Settings.Default.ArchivoCostosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CostoEntrado> CostoEntrado
		{
			get
			{
				return this.GetTable<CostoEntrado>();
			}
		}
		
		public System.Data.Linq.Table<Salidas> Salidas
		{
			get
			{
				return this.GetTable<Salidas>();
			}
		}
		
		public System.Data.Linq.Table<CostosPorFechas> CostosPorFechas
		{
			get
			{
				return this.GetTable<CostosPorFechas>();
			}
		}
		
		public System.Data.Linq.Table<Fechas> Fechas
		{
			get
			{
				return this.GetTable<Fechas>();
			}
		}
		
		public System.Data.Linq.Table<Ordenes> Ordenes
		{
			get
			{
				return this.GetTable<Ordenes>();
			}
		}
		
		public System.Data.Linq.Table<Pedidos> Pedidos
		{
			get
			{
				return this.GetTable<Pedidos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UltimaFechaInsertada")]
		public int UltimaFechaInsertada()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarFechas")]
		public int InsertarFechas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Proyecto", DbType="VarChar(50)")] string proyecto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(20)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] ref string mjs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), proyecto, fecha, tipo, mjs);
			mjs = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CostoEntrado")]
	public partial class CostoEntrado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _referencia1;
		
		private string _nombppto;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _orden;
		
		private string _Nliqu;
		
		private string _codterc;
		
		private string _nombre;
		
		private string _cap;
		
		private string _nombrecap;
		
		private string _apu;
		
		private string _nombapu;
		
		private string _codigo;
		
		private string _descripcion;
		
		private string _unidad;
		
		private System.Nullable<decimal> _cantent;
		
		private System.Nullable<decimal> _vlrunitentrado;
		
		private System.Nullable<decimal> _costoentrado1;
		
		private string _usuario;
		
		private System.Nullable<int> _IdFecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onreferencia1Changing(string value);
    partial void Onreferencia1Changed();
    partial void OnnombpptoChanging(string value);
    partial void OnnombpptoChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnordenChanging(string value);
    partial void OnordenChanged();
    partial void OnNliquChanging(string value);
    partial void OnNliquChanged();
    partial void OncodtercChanging(string value);
    partial void OncodtercChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncapChanging(string value);
    partial void OncapChanged();
    partial void OnnombrecapChanging(string value);
    partial void OnnombrecapChanged();
    partial void OnapuChanging(string value);
    partial void OnapuChanged();
    partial void OnnombapuChanging(string value);
    partial void OnnombapuChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnunidadChanging(string value);
    partial void OnunidadChanged();
    partial void OncantentChanging(System.Nullable<decimal> value);
    partial void OncantentChanged();
    partial void OnvlrunitentradoChanging(System.Nullable<decimal> value);
    partial void OnvlrunitentradoChanged();
    partial void Oncostoentrado1Changing(System.Nullable<decimal> value);
    partial void Oncostoentrado1Changed();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnIdFechaChanging(System.Nullable<int> value);
    partial void OnIdFechaChanged();
    #endregion
		
		public CostoEntrado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia1", DbType="VarChar(20)")]
		public string referencia1
		{
			get
			{
				return this._referencia1;
			}
			set
			{
				if ((this._referencia1 != value))
				{
					this.Onreferencia1Changing(value);
					this.SendPropertyChanging();
					this._referencia1 = value;
					this.SendPropertyChanged("referencia1");
					this.Onreferencia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombppto", DbType="VarChar(300)")]
		public string nombppto
		{
			get
			{
				return this._nombppto;
			}
			set
			{
				if ((this._nombppto != value))
				{
					this.OnnombpptoChanging(value);
					this.SendPropertyChanging();
					this._nombppto = value;
					this.SendPropertyChanged("nombppto");
					this.OnnombpptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orden", DbType="VarChar(15)")]
		public string orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				if ((this._orden != value))
				{
					this.OnordenChanging(value);
					this.SendPropertyChanging();
					this._orden = value;
					this.SendPropertyChanged("orden");
					this.OnordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nliqu", DbType="VarChar(6)")]
		public string Nliqu
		{
			get
			{
				return this._Nliqu;
			}
			set
			{
				if ((this._Nliqu != value))
				{
					this.OnNliquChanging(value);
					this.SendPropertyChanging();
					this._Nliqu = value;
					this.SendPropertyChanged("Nliqu");
					this.OnNliquChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codterc", DbType="NVarChar(5)")]
		public string codterc
		{
			get
			{
				return this._codterc;
			}
			set
			{
				if ((this._codterc != value))
				{
					this.OncodtercChanging(value);
					this.SendPropertyChanging();
					this._codterc = value;
					this.SendPropertyChanged("codterc");
					this.OncodtercChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cap", DbType="VarChar(4)")]
		public string cap
		{
			get
			{
				return this._cap;
			}
			set
			{
				if ((this._cap != value))
				{
					this.OncapChanging(value);
					this.SendPropertyChanging();
					this._cap = value;
					this.SendPropertyChanged("cap");
					this.OncapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecap", DbType="VarChar(250)")]
		public string nombrecap
		{
			get
			{
				return this._nombrecap;
			}
			set
			{
				if ((this._nombrecap != value))
				{
					this.OnnombrecapChanging(value);
					this.SendPropertyChanging();
					this._nombrecap = value;
					this.SendPropertyChanged("nombrecap");
					this.OnnombrecapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apu", DbType="VarChar(6)")]
		public string apu
		{
			get
			{
				return this._apu;
			}
			set
			{
				if ((this._apu != value))
				{
					this.OnapuChanging(value);
					this.SendPropertyChanging();
					this._apu = value;
					this.SendPropertyChanged("apu");
					this.OnapuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombapu", DbType="VarChar(250)")]
		public string nombapu
		{
			get
			{
				return this._nombapu;
			}
			set
			{
				if ((this._nombapu != value))
				{
					this.OnnombapuChanging(value);
					this.SendPropertyChanging();
					this._nombapu = value;
					this.SendPropertyChanged("nombapu");
					this.OnnombapuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(5)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidad", DbType="VarChar(5)")]
		public string unidad
		{
			get
			{
				return this._unidad;
			}
			set
			{
				if ((this._unidad != value))
				{
					this.OnunidadChanging(value);
					this.SendPropertyChanging();
					this._unidad = value;
					this.SendPropertyChanged("unidad");
					this.OnunidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantent", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> cantent
		{
			get
			{
				return this._cantent;
			}
			set
			{
				if ((this._cantent != value))
				{
					this.OncantentChanging(value);
					this.SendPropertyChanging();
					this._cantent = value;
					this.SendPropertyChanged("cantent");
					this.OncantentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrunitentrado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrunitentrado
		{
			get
			{
				return this._vlrunitentrado;
			}
			set
			{
				if ((this._vlrunitentrado != value))
				{
					this.OnvlrunitentradoChanging(value);
					this.SendPropertyChanging();
					this._vlrunitentrado = value;
					this.SendPropertyChanged("vlrunitentrado");
					this.OnvlrunitentradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="costoentrado", Storage="_costoentrado1", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> costoentrado1
		{
			get
			{
				return this._costoentrado1;
			}
			set
			{
				if ((this._costoentrado1 != value))
				{
					this.Oncostoentrado1Changing(value);
					this.SendPropertyChanging();
					this._costoentrado1 = value;
					this.SendPropertyChanged("costoentrado1");
					this.Oncostoentrado1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFecha", DbType="Int")]
		public System.Nullable<int> IdFecha
		{
			get
			{
				return this._IdFecha;
			}
			set
			{
				if ((this._IdFecha != value))
				{
					this.OnIdFechaChanging(value);
					this.SendPropertyChanging();
					this._IdFecha = value;
					this.SendPropertyChanged("IdFecha");
					this.OnIdFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Salidas")]
	public partial class Salidas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _referencia;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _liquidacion;
		
		private string _valeconsumo;
		
		private string _salida;
		
		private System.Nullable<char> _tiposa;
		
		private string _codcapi;
		
		private string _codunita;
		
		private string _codinsum;
		
		private string _insumo;
		
		private System.Nullable<decimal> _cant;
		
		private System.Nullable<decimal> _costsali;
		
		private string _saliobse;
		
		private string _saliusua;
		
		private System.Nullable<int> _IdFecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnreferenciaChanging(string value);
    partial void OnreferenciaChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnliquidacionChanging(string value);
    partial void OnliquidacionChanged();
    partial void OnvaleconsumoChanging(string value);
    partial void OnvaleconsumoChanged();
    partial void OnsalidaChanging(string value);
    partial void OnsalidaChanged();
    partial void OntiposaChanging(System.Nullable<char> value);
    partial void OntiposaChanged();
    partial void OncodcapiChanging(string value);
    partial void OncodcapiChanged();
    partial void OncodunitaChanging(string value);
    partial void OncodunitaChanged();
    partial void OncodinsumChanging(string value);
    partial void OncodinsumChanged();
    partial void OninsumoChanging(string value);
    partial void OninsumoChanged();
    partial void OncantChanging(System.Nullable<decimal> value);
    partial void OncantChanged();
    partial void OncostsaliChanging(System.Nullable<decimal> value);
    partial void OncostsaliChanged();
    partial void OnsaliobseChanging(string value);
    partial void OnsaliobseChanged();
    partial void OnsaliusuaChanging(string value);
    partial void OnsaliusuaChanged();
    partial void OnIdFechaChanging(System.Nullable<int> value);
    partial void OnIdFechaChanged();
    #endregion
		
		public Salidas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia", DbType="VarChar(20)")]
		public string referencia
		{
			get
			{
				return this._referencia;
			}
			set
			{
				if ((this._referencia != value))
				{
					this.OnreferenciaChanging(value);
					this.SendPropertyChanging();
					this._referencia = value;
					this.SendPropertyChanged("referencia");
					this.OnreferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liquidacion", DbType="VarChar(8)")]
		public string liquidacion
		{
			get
			{
				return this._liquidacion;
			}
			set
			{
				if ((this._liquidacion != value))
				{
					this.OnliquidacionChanging(value);
					this.SendPropertyChanging();
					this._liquidacion = value;
					this.SendPropertyChanged("liquidacion");
					this.OnliquidacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valeconsumo", DbType="VarChar(8)")]
		public string valeconsumo
		{
			get
			{
				return this._valeconsumo;
			}
			set
			{
				if ((this._valeconsumo != value))
				{
					this.OnvaleconsumoChanging(value);
					this.SendPropertyChanging();
					this._valeconsumo = value;
					this.SendPropertyChanged("valeconsumo");
					this.OnvaleconsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salida", DbType="VarChar(8)")]
		public string salida
		{
			get
			{
				return this._salida;
			}
			set
			{
				if ((this._salida != value))
				{
					this.OnsalidaChanging(value);
					this.SendPropertyChanging();
					this._salida = value;
					this.SendPropertyChanged("salida");
					this.OnsalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiposa", DbType="Char(1)")]
		public System.Nullable<char> tiposa
		{
			get
			{
				return this._tiposa;
			}
			set
			{
				if ((this._tiposa != value))
				{
					this.OntiposaChanging(value);
					this.SendPropertyChanging();
					this._tiposa = value;
					this.SendPropertyChanged("tiposa");
					this.OntiposaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codcapi", DbType="VarChar(6)")]
		public string codcapi
		{
			get
			{
				return this._codcapi;
			}
			set
			{
				if ((this._codcapi != value))
				{
					this.OncodcapiChanging(value);
					this.SendPropertyChanging();
					this._codcapi = value;
					this.SendPropertyChanged("codcapi");
					this.OncodcapiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codunita", DbType="VarChar(6)")]
		public string codunita
		{
			get
			{
				return this._codunita;
			}
			set
			{
				if ((this._codunita != value))
				{
					this.OncodunitaChanging(value);
					this.SendPropertyChanging();
					this._codunita = value;
					this.SendPropertyChanged("codunita");
					this.OncodunitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codinsum", DbType="VarChar(6)")]
		public string codinsum
		{
			get
			{
				return this._codinsum;
			}
			set
			{
				if ((this._codinsum != value))
				{
					this.OncodinsumChanging(value);
					this.SendPropertyChanging();
					this._codinsum = value;
					this.SendPropertyChanged("codinsum");
					this.OncodinsumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insumo", DbType="VarChar(250)")]
		public string insumo
		{
			get
			{
				return this._insumo;
			}
			set
			{
				if ((this._insumo != value))
				{
					this.OninsumoChanging(value);
					this.SendPropertyChanging();
					this._insumo = value;
					this.SendPropertyChanged("insumo");
					this.OninsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cant", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> cant
		{
			get
			{
				return this._cant;
			}
			set
			{
				if ((this._cant != value))
				{
					this.OncantChanging(value);
					this.SendPropertyChanging();
					this._cant = value;
					this.SendPropertyChanged("cant");
					this.OncantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costsali", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> costsali
		{
			get
			{
				return this._costsali;
			}
			set
			{
				if ((this._costsali != value))
				{
					this.OncostsaliChanging(value);
					this.SendPropertyChanging();
					this._costsali = value;
					this.SendPropertyChanged("costsali");
					this.OncostsaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saliobse", DbType="VarChar(250)")]
		public string saliobse
		{
			get
			{
				return this._saliobse;
			}
			set
			{
				if ((this._saliobse != value))
				{
					this.OnsaliobseChanging(value);
					this.SendPropertyChanging();
					this._saliobse = value;
					this.SendPropertyChanged("saliobse");
					this.OnsaliobseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saliusua", DbType="VarChar(50)")]
		public string saliusua
		{
			get
			{
				return this._saliusua;
			}
			set
			{
				if ((this._saliusua != value))
				{
					this.OnsaliusuaChanging(value);
					this.SendPropertyChanging();
					this._saliusua = value;
					this.SendPropertyChanged("saliusua");
					this.OnsaliusuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFecha", DbType="Int")]
		public System.Nullable<int> IdFecha
		{
			get
			{
				return this._IdFecha;
			}
			set
			{
				if ((this._IdFecha != value))
				{
					this.OnIdFechaChanging(value);
					this.SendPropertyChanging();
					this._IdFecha = value;
					this.SendPropertyChanged("IdFecha");
					this.OnIdFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CostosPorFechas")]
	public partial class CostosPorFechas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _refe;
		
		private string _referencia2;
		
		private string _referencia3;
		
		private string _presupuesto;
		
		private string _codcapi;
		
		private string _capitulo;
		
		private string _codunit;
		
		private string _unitario;
		
		private string _undunita;
		
		private System.Nullable<decimal> _cantxppto;
		
		private string _codinsu;
		
		private string _insutipo;
		
		private string _insumo;
		
		private string _unidinsu;
		
		private string _ctrlinven;
		
		private string _validación;
		
		private System.Nullable<decimal> _precioppto;
		
		private System.Nullable<decimal> _consumounitario;
		
		private System.Nullable<decimal> _consumototal;
		
		private System.Nullable<decimal> _adic;
		
		private System.Nullable<decimal> _precioaut;
		
		private System.Nullable<decimal> _PrecioCompra;
		
		private System.Nullable<decimal> _PrecioEntrado;
		
		private System.Nullable<decimal> _Ped;
		
		private System.Nullable<decimal> _aprob;
		
		private System.Nullable<decimal> _comp;
		
		private System.Nullable<decimal> _ent;
		
		private System.Nullable<decimal> _sali;
		
		private System.Nullable<decimal> _traslado;
		
		private System.Nullable<decimal> _xcomp;
		
		private System.Nullable<decimal> _xent;
		
		private System.Nullable<decimal> _saldoxunit;
		
		private System.Nullable<decimal> _SaldoXppto;
		
		private System.Nullable<decimal> _vlrEnt;
		
		private System.Nullable<decimal> _vlrEnttraslado;
		
		private System.Nullable<decimal> _VlrCompradoxent;
		
		private System.Nullable<decimal> _vlrxcomp;
		
		private System.Nullable<decimal> _VlrTraslado;
		
		private System.Nullable<decimal> _vlrproy;
		
		private System.Nullable<decimal> _vlrproyejec;
		
		private System.Nullable<decimal> _Vlrini;
		
		private System.Nullable<decimal> _vlrejec;
		
		private System.Nullable<int> _IdFecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnrefeChanging(string value);
    partial void OnrefeChanged();
    partial void Onreferencia2Changing(string value);
    partial void Onreferencia2Changed();
    partial void Onreferencia3Changing(string value);
    partial void Onreferencia3Changed();
    partial void OnpresupuestoChanging(string value);
    partial void OnpresupuestoChanged();
    partial void OncodcapiChanging(string value);
    partial void OncodcapiChanged();
    partial void OncapituloChanging(string value);
    partial void OncapituloChanged();
    partial void OncodunitChanging(string value);
    partial void OncodunitChanged();
    partial void OnunitarioChanging(string value);
    partial void OnunitarioChanged();
    partial void OnundunitaChanging(string value);
    partial void OnundunitaChanged();
    partial void OncantxpptoChanging(System.Nullable<decimal> value);
    partial void OncantxpptoChanged();
    partial void OncodinsuChanging(string value);
    partial void OncodinsuChanged();
    partial void OninsutipoChanging(string value);
    partial void OninsutipoChanged();
    partial void OninsumoChanging(string value);
    partial void OninsumoChanged();
    partial void OnunidinsuChanging(string value);
    partial void OnunidinsuChanged();
    partial void OnctrlinvenChanging(string value);
    partial void OnctrlinvenChanged();
    partial void OnvalidaciónChanging(string value);
    partial void OnvalidaciónChanged();
    partial void OnpreciopptoChanging(System.Nullable<decimal> value);
    partial void OnpreciopptoChanged();
    partial void OnconsumounitarioChanging(System.Nullable<decimal> value);
    partial void OnconsumounitarioChanged();
    partial void OnconsumototalChanging(System.Nullable<decimal> value);
    partial void OnconsumototalChanged();
    partial void OnadicChanging(System.Nullable<decimal> value);
    partial void OnadicChanged();
    partial void OnprecioautChanging(System.Nullable<decimal> value);
    partial void OnprecioautChanged();
    partial void OnPrecioCompraChanging(System.Nullable<decimal> value);
    partial void OnPrecioCompraChanged();
    partial void OnPrecioEntradoChanging(System.Nullable<decimal> value);
    partial void OnPrecioEntradoChanged();
    partial void OnPedChanging(System.Nullable<decimal> value);
    partial void OnPedChanged();
    partial void OnaprobChanging(System.Nullable<decimal> value);
    partial void OnaprobChanged();
    partial void OncompChanging(System.Nullable<decimal> value);
    partial void OncompChanged();
    partial void OnentChanging(System.Nullable<decimal> value);
    partial void OnentChanged();
    partial void OnsaliChanging(System.Nullable<decimal> value);
    partial void OnsaliChanged();
    partial void OntrasladoChanging(System.Nullable<decimal> value);
    partial void OntrasladoChanged();
    partial void OnxcompChanging(System.Nullable<decimal> value);
    partial void OnxcompChanged();
    partial void OnxentChanging(System.Nullable<decimal> value);
    partial void OnxentChanged();
    partial void OnsaldoxunitChanging(System.Nullable<decimal> value);
    partial void OnsaldoxunitChanged();
    partial void OnSaldoXpptoChanging(System.Nullable<decimal> value);
    partial void OnSaldoXpptoChanged();
    partial void OnvlrEntChanging(System.Nullable<decimal> value);
    partial void OnvlrEntChanged();
    partial void OnvlrEnttrasladoChanging(System.Nullable<decimal> value);
    partial void OnvlrEnttrasladoChanged();
    partial void OnVlrCompradoxentChanging(System.Nullable<decimal> value);
    partial void OnVlrCompradoxentChanged();
    partial void OnvlrxcompChanging(System.Nullable<decimal> value);
    partial void OnvlrxcompChanged();
    partial void OnVlrTrasladoChanging(System.Nullable<decimal> value);
    partial void OnVlrTrasladoChanged();
    partial void OnvlrproyChanging(System.Nullable<decimal> value);
    partial void OnvlrproyChanged();
    partial void OnvlrproyejecChanging(System.Nullable<decimal> value);
    partial void OnvlrproyejecChanged();
    partial void OnVlriniChanging(System.Nullable<decimal> value);
    partial void OnVlriniChanged();
    partial void OnvlrejecChanging(System.Nullable<decimal> value);
    partial void OnvlrejecChanged();
    partial void OnIdFechaChanging(System.Nullable<int> value);
    partial void OnIdFechaChanged();
    #endregion
		
		public CostosPorFechas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refe", DbType="VarChar(30)")]
		public string refe
		{
			get
			{
				return this._refe;
			}
			set
			{
				if ((this._refe != value))
				{
					this.OnrefeChanging(value);
					this.SendPropertyChanging();
					this._refe = value;
					this.SendPropertyChanged("refe");
					this.OnrefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia2", DbType="VarChar(30)")]
		public string referencia2
		{
			get
			{
				return this._referencia2;
			}
			set
			{
				if ((this._referencia2 != value))
				{
					this.Onreferencia2Changing(value);
					this.SendPropertyChanging();
					this._referencia2 = value;
					this.SendPropertyChanged("referencia2");
					this.Onreferencia2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia3", DbType="VarChar(30)")]
		public string referencia3
		{
			get
			{
				return this._referencia3;
			}
			set
			{
				if ((this._referencia3 != value))
				{
					this.Onreferencia3Changing(value);
					this.SendPropertyChanging();
					this._referencia3 = value;
					this.SendPropertyChanged("referencia3");
					this.Onreferencia3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presupuesto", DbType="VarChar(250)")]
		public string presupuesto
		{
			get
			{
				return this._presupuesto;
			}
			set
			{
				if ((this._presupuesto != value))
				{
					this.OnpresupuestoChanging(value);
					this.SendPropertyChanging();
					this._presupuesto = value;
					this.SendPropertyChanged("presupuesto");
					this.OnpresupuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codcapi", DbType="VarChar(10)")]
		public string codcapi
		{
			get
			{
				return this._codcapi;
			}
			set
			{
				if ((this._codcapi != value))
				{
					this.OncodcapiChanging(value);
					this.SendPropertyChanging();
					this._codcapi = value;
					this.SendPropertyChanged("codcapi");
					this.OncodcapiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capitulo", DbType="VarChar(250)")]
		public string capitulo
		{
			get
			{
				return this._capitulo;
			}
			set
			{
				if ((this._capitulo != value))
				{
					this.OncapituloChanging(value);
					this.SendPropertyChanging();
					this._capitulo = value;
					this.SendPropertyChanged("capitulo");
					this.OncapituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codunit", DbType="VarChar(10)")]
		public string codunit
		{
			get
			{
				return this._codunit;
			}
			set
			{
				if ((this._codunit != value))
				{
					this.OncodunitChanging(value);
					this.SendPropertyChanging();
					this._codunit = value;
					this.SendPropertyChanged("codunit");
					this.OncodunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitario", DbType="VarChar(250)")]
		public string unitario
		{
			get
			{
				return this._unitario;
			}
			set
			{
				if ((this._unitario != value))
				{
					this.OnunitarioChanging(value);
					this.SendPropertyChanging();
					this._unitario = value;
					this.SendPropertyChanged("unitario");
					this.OnunitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_undunita", DbType="VarChar(10)")]
		public string undunita
		{
			get
			{
				return this._undunita;
			}
			set
			{
				if ((this._undunita != value))
				{
					this.OnundunitaChanging(value);
					this.SendPropertyChanging();
					this._undunita = value;
					this.SendPropertyChanged("undunita");
					this.OnundunitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantxppto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> cantxppto
		{
			get
			{
				return this._cantxppto;
			}
			set
			{
				if ((this._cantxppto != value))
				{
					this.OncantxpptoChanging(value);
					this.SendPropertyChanging();
					this._cantxppto = value;
					this.SendPropertyChanged("cantxppto");
					this.OncantxpptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codinsu", DbType="VarChar(10)")]
		public string codinsu
		{
			get
			{
				return this._codinsu;
			}
			set
			{
				if ((this._codinsu != value))
				{
					this.OncodinsuChanging(value);
					this.SendPropertyChanging();
					this._codinsu = value;
					this.SendPropertyChanged("codinsu");
					this.OncodinsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insutipo", DbType="VarChar(10)")]
		public string insutipo
		{
			get
			{
				return this._insutipo;
			}
			set
			{
				if ((this._insutipo != value))
				{
					this.OninsutipoChanging(value);
					this.SendPropertyChanging();
					this._insutipo = value;
					this.SendPropertyChanged("insutipo");
					this.OninsutipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insumo", DbType="VarChar(250)")]
		public string insumo
		{
			get
			{
				return this._insumo;
			}
			set
			{
				if ((this._insumo != value))
				{
					this.OninsumoChanging(value);
					this.SendPropertyChanging();
					this._insumo = value;
					this.SendPropertyChanged("insumo");
					this.OninsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidinsu", DbType="VarChar(10)")]
		public string unidinsu
		{
			get
			{
				return this._unidinsu;
			}
			set
			{
				if ((this._unidinsu != value))
				{
					this.OnunidinsuChanging(value);
					this.SendPropertyChanging();
					this._unidinsu = value;
					this.SendPropertyChanged("unidinsu");
					this.OnunidinsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctrlinven", DbType="VarChar(6)")]
		public string ctrlinven
		{
			get
			{
				return this._ctrlinven;
			}
			set
			{
				if ((this._ctrlinven != value))
				{
					this.OnctrlinvenChanging(value);
					this.SendPropertyChanging();
					this._ctrlinven = value;
					this.SendPropertyChanged("ctrlinven");
					this.OnctrlinvenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validación", DbType="VarChar(6)")]
		public string validación
		{
			get
			{
				return this._validación;
			}
			set
			{
				if ((this._validación != value))
				{
					this.OnvalidaciónChanging(value);
					this.SendPropertyChanging();
					this._validación = value;
					this.SendPropertyChanged("validación");
					this.OnvalidaciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioppto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> precioppto
		{
			get
			{
				return this._precioppto;
			}
			set
			{
				if ((this._precioppto != value))
				{
					this.OnpreciopptoChanging(value);
					this.SendPropertyChanging();
					this._precioppto = value;
					this.SendPropertyChanged("precioppto");
					this.OnpreciopptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consumounitario", DbType="Decimal(20,3)")]
		public System.Nullable<decimal> consumounitario
		{
			get
			{
				return this._consumounitario;
			}
			set
			{
				if ((this._consumounitario != value))
				{
					this.OnconsumounitarioChanging(value);
					this.SendPropertyChanging();
					this._consumounitario = value;
					this.SendPropertyChanged("consumounitario");
					this.OnconsumounitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consumototal", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> consumototal
		{
			get
			{
				return this._consumototal;
			}
			set
			{
				if ((this._consumototal != value))
				{
					this.OnconsumototalChanging(value);
					this.SendPropertyChanging();
					this._consumototal = value;
					this.SendPropertyChanged("consumototal");
					this.OnconsumototalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adic", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> adic
		{
			get
			{
				return this._adic;
			}
			set
			{
				if ((this._adic != value))
				{
					this.OnadicChanging(value);
					this.SendPropertyChanging();
					this._adic = value;
					this.SendPropertyChanged("adic");
					this.OnadicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioaut", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> precioaut
		{
			get
			{
				return this._precioaut;
			}
			set
			{
				if ((this._precioaut != value))
				{
					this.OnprecioautChanging(value);
					this.SendPropertyChanging();
					this._precioaut = value;
					this.SendPropertyChanged("precioaut");
					this.OnprecioautChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompra", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioCompra
		{
			get
			{
				return this._PrecioCompra;
			}
			set
			{
				if ((this._PrecioCompra != value))
				{
					this.OnPrecioCompraChanging(value);
					this.SendPropertyChanging();
					this._PrecioCompra = value;
					this.SendPropertyChanged("PrecioCompra");
					this.OnPrecioCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioEntrado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioEntrado
		{
			get
			{
				return this._PrecioEntrado;
			}
			set
			{
				if ((this._PrecioEntrado != value))
				{
					this.OnPrecioEntradoChanging(value);
					this.SendPropertyChanging();
					this._PrecioEntrado = value;
					this.SendPropertyChanged("PrecioEntrado");
					this.OnPrecioEntradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ped", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Ped
		{
			get
			{
				return this._Ped;
			}
			set
			{
				if ((this._Ped != value))
				{
					this.OnPedChanging(value);
					this.SendPropertyChanging();
					this._Ped = value;
					this.SendPropertyChanged("Ped");
					this.OnPedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aprob", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> aprob
		{
			get
			{
				return this._aprob;
			}
			set
			{
				if ((this._aprob != value))
				{
					this.OnaprobChanging(value);
					this.SendPropertyChanging();
					this._aprob = value;
					this.SendPropertyChanged("aprob");
					this.OnaprobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> comp
		{
			get
			{
				return this._comp;
			}
			set
			{
				if ((this._comp != value))
				{
					this.OncompChanging(value);
					this.SendPropertyChanging();
					this._comp = value;
					this.SendPropertyChanged("comp");
					this.OncompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ent", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ent
		{
			get
			{
				return this._ent;
			}
			set
			{
				if ((this._ent != value))
				{
					this.OnentChanging(value);
					this.SendPropertyChanging();
					this._ent = value;
					this.SendPropertyChanged("ent");
					this.OnentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sali", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> sali
		{
			get
			{
				return this._sali;
			}
			set
			{
				if ((this._sali != value))
				{
					this.OnsaliChanging(value);
					this.SendPropertyChanging();
					this._sali = value;
					this.SendPropertyChanged("sali");
					this.OnsaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traslado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> traslado
		{
			get
			{
				return this._traslado;
			}
			set
			{
				if ((this._traslado != value))
				{
					this.OntrasladoChanging(value);
					this.SendPropertyChanging();
					this._traslado = value;
					this.SendPropertyChanged("traslado");
					this.OntrasladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xcomp", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> xcomp
		{
			get
			{
				return this._xcomp;
			}
			set
			{
				if ((this._xcomp != value))
				{
					this.OnxcompChanging(value);
					this.SendPropertyChanging();
					this._xcomp = value;
					this.SendPropertyChanged("xcomp");
					this.OnxcompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xent", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> xent
		{
			get
			{
				return this._xent;
			}
			set
			{
				if ((this._xent != value))
				{
					this.OnxentChanging(value);
					this.SendPropertyChanging();
					this._xent = value;
					this.SendPropertyChanged("xent");
					this.OnxentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoxunit", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> saldoxunit
		{
			get
			{
				return this._saldoxunit;
			}
			set
			{
				if ((this._saldoxunit != value))
				{
					this.OnsaldoxunitChanging(value);
					this.SendPropertyChanging();
					this._saldoxunit = value;
					this.SendPropertyChanged("saldoxunit");
					this.OnsaldoxunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoXppto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SaldoXppto
		{
			get
			{
				return this._SaldoXppto;
			}
			set
			{
				if ((this._SaldoXppto != value))
				{
					this.OnSaldoXpptoChanging(value);
					this.SendPropertyChanging();
					this._SaldoXppto = value;
					this.SendPropertyChanged("SaldoXppto");
					this.OnSaldoXpptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrEnt", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrEnt
		{
			get
			{
				return this._vlrEnt;
			}
			set
			{
				if ((this._vlrEnt != value))
				{
					this.OnvlrEntChanging(value);
					this.SendPropertyChanging();
					this._vlrEnt = value;
					this.SendPropertyChanged("vlrEnt");
					this.OnvlrEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrEnttraslado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrEnttraslado
		{
			get
			{
				return this._vlrEnttraslado;
			}
			set
			{
				if ((this._vlrEnttraslado != value))
				{
					this.OnvlrEnttrasladoChanging(value);
					this.SendPropertyChanging();
					this._vlrEnttraslado = value;
					this.SendPropertyChanged("vlrEnttraslado");
					this.OnvlrEnttrasladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VlrCompradoxent", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VlrCompradoxent
		{
			get
			{
				return this._VlrCompradoxent;
			}
			set
			{
				if ((this._VlrCompradoxent != value))
				{
					this.OnVlrCompradoxentChanging(value);
					this.SendPropertyChanging();
					this._VlrCompradoxent = value;
					this.SendPropertyChanged("VlrCompradoxent");
					this.OnVlrCompradoxentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrxcomp", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrxcomp
		{
			get
			{
				return this._vlrxcomp;
			}
			set
			{
				if ((this._vlrxcomp != value))
				{
					this.OnvlrxcompChanging(value);
					this.SendPropertyChanging();
					this._vlrxcomp = value;
					this.SendPropertyChanged("vlrxcomp");
					this.OnvlrxcompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VlrTraslado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VlrTraslado
		{
			get
			{
				return this._VlrTraslado;
			}
			set
			{
				if ((this._VlrTraslado != value))
				{
					this.OnVlrTrasladoChanging(value);
					this.SendPropertyChanging();
					this._VlrTraslado = value;
					this.SendPropertyChanged("VlrTraslado");
					this.OnVlrTrasladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrproy", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrproy
		{
			get
			{
				return this._vlrproy;
			}
			set
			{
				if ((this._vlrproy != value))
				{
					this.OnvlrproyChanging(value);
					this.SendPropertyChanging();
					this._vlrproy = value;
					this.SendPropertyChanged("vlrproy");
					this.OnvlrproyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrproyejec", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrproyejec
		{
			get
			{
				return this._vlrproyejec;
			}
			set
			{
				if ((this._vlrproyejec != value))
				{
					this.OnvlrproyejecChanging(value);
					this.SendPropertyChanging();
					this._vlrproyejec = value;
					this.SendPropertyChanged("vlrproyejec");
					this.OnvlrproyejecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vlrini", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Vlrini
		{
			get
			{
				return this._Vlrini;
			}
			set
			{
				if ((this._Vlrini != value))
				{
					this.OnVlriniChanging(value);
					this.SendPropertyChanging();
					this._Vlrini = value;
					this.SendPropertyChanged("Vlrini");
					this.OnVlriniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlrejec", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> vlrejec
		{
			get
			{
				return this._vlrejec;
			}
			set
			{
				if ((this._vlrejec != value))
				{
					this.OnvlrejecChanging(value);
					this.SendPropertyChanging();
					this._vlrejec = value;
					this.SendPropertyChanged("vlrejec");
					this.OnvlrejecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFecha", DbType="Int")]
		public System.Nullable<int> IdFecha
		{
			get
			{
				return this._IdFecha;
			}
			set
			{
				if ((this._IdFecha != value))
				{
					this.OnIdFechaChanging(value);
					this.SendPropertyChanging();
					this._IdFecha = value;
					this.SendPropertyChanged("IdFecha");
					this.OnIdFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fechas")]
	public partial class Fechas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Proyecto;
		
		private string _Tipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnProyectoChanging(string value);
    partial void OnProyectoChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public Fechas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proyecto", DbType="VarChar(6)")]
		public string Proyecto
		{
			get
			{
				return this._Proyecto;
			}
			set
			{
				if ((this._Proyecto != value))
				{
					this.OnProyectoChanging(value);
					this.SendPropertyChanging();
					this._Proyecto = value;
					this.SendPropertyChanged("Proyecto");
					this.OnProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ordenes")]
	public partial class Ordenes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Referencia1;
		
		private string _Presupuesto;
		
		private string _Cod_Unit;
		
		private string _Unitario;
		
		private string _Cod_Insumo;
		
		private string _Insumo;
		
		private string _Und;
		
		private System.Nullable<decimal> _Comp;
		
		private System.Nullable<decimal> _Ent;
		
		private System.Nullable<decimal> _PorEnt;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Orden;
		
		private System.Nullable<char> _Tipo;
		
		private string _Cod_Prov;
		
		private string _Proveedor;
		
		private System.Nullable<decimal> _VlrUnita;
		
		private System.Nullable<decimal> _CostEnt;
		
		private string _Usuario;
		
		private System.Nullable<int> _IdFecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnReferencia1Changing(string value);
    partial void OnReferencia1Changed();
    partial void OnPresupuestoChanging(string value);
    partial void OnPresupuestoChanged();
    partial void OnCod_UnitChanging(string value);
    partial void OnCod_UnitChanged();
    partial void OnUnitarioChanging(string value);
    partial void OnUnitarioChanged();
    partial void OnCod_InsumoChanging(string value);
    partial void OnCod_InsumoChanged();
    partial void OnInsumoChanging(string value);
    partial void OnInsumoChanged();
    partial void OnUndChanging(string value);
    partial void OnUndChanged();
    partial void OnCompChanging(System.Nullable<decimal> value);
    partial void OnCompChanged();
    partial void OnEntChanging(System.Nullable<decimal> value);
    partial void OnEntChanged();
    partial void OnPorEntChanging(System.Nullable<decimal> value);
    partial void OnPorEntChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnOrdenChanging(string value);
    partial void OnOrdenChanged();
    partial void OnTipoChanging(System.Nullable<char> value);
    partial void OnTipoChanged();
    partial void OnCod_ProvChanging(string value);
    partial void OnCod_ProvChanged();
    partial void OnProveedorChanging(string value);
    partial void OnProveedorChanged();
    partial void OnVlrUnitaChanging(System.Nullable<decimal> value);
    partial void OnVlrUnitaChanged();
    partial void OnCostEntChanging(System.Nullable<decimal> value);
    partial void OnCostEntChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnIdFechaChanging(System.Nullable<int> value);
    partial void OnIdFechaChanged();
    #endregion
		
		public Ordenes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia1", DbType="VarChar(20)")]
		public string Referencia1
		{
			get
			{
				return this._Referencia1;
			}
			set
			{
				if ((this._Referencia1 != value))
				{
					this.OnReferencia1Changing(value);
					this.SendPropertyChanging();
					this._Referencia1 = value;
					this.SendPropertyChanged("Referencia1");
					this.OnReferencia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presupuesto", DbType="VarChar(100)")]
		public string Presupuesto
		{
			get
			{
				return this._Presupuesto;
			}
			set
			{
				if ((this._Presupuesto != value))
				{
					this.OnPresupuestoChanging(value);
					this.SendPropertyChanging();
					this._Presupuesto = value;
					this.SendPropertyChanged("Presupuesto");
					this.OnPresupuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Unit", DbType="VarChar(6)")]
		public string Cod_Unit
		{
			get
			{
				return this._Cod_Unit;
			}
			set
			{
				if ((this._Cod_Unit != value))
				{
					this.OnCod_UnitChanging(value);
					this.SendPropertyChanging();
					this._Cod_Unit = value;
					this.SendPropertyChanged("Cod_Unit");
					this.OnCod_UnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unitario", DbType="VarChar(100)")]
		public string Unitario
		{
			get
			{
				return this._Unitario;
			}
			set
			{
				if ((this._Unitario != value))
				{
					this.OnUnitarioChanging(value);
					this.SendPropertyChanging();
					this._Unitario = value;
					this.SendPropertyChanged("Unitario");
					this.OnUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Insumo", DbType="VarChar(6)")]
		public string Cod_Insumo
		{
			get
			{
				return this._Cod_Insumo;
			}
			set
			{
				if ((this._Cod_Insumo != value))
				{
					this.OnCod_InsumoChanging(value);
					this.SendPropertyChanging();
					this._Cod_Insumo = value;
					this.SendPropertyChanged("Cod_Insumo");
					this.OnCod_InsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insumo", DbType="VarChar(100)")]
		public string Insumo
		{
			get
			{
				return this._Insumo;
			}
			set
			{
				if ((this._Insumo != value))
				{
					this.OnInsumoChanging(value);
					this.SendPropertyChanging();
					this._Insumo = value;
					this.SendPropertyChanged("Insumo");
					this.OnInsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Und", DbType="VarChar(4)")]
		public string Und
		{
			get
			{
				return this._Und;
			}
			set
			{
				if ((this._Und != value))
				{
					this.OnUndChanging(value);
					this.SendPropertyChanging();
					this._Und = value;
					this.SendPropertyChanged("Und");
					this.OnUndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> Comp
		{
			get
			{
				return this._Comp;
			}
			set
			{
				if ((this._Comp != value))
				{
					this.OnCompChanging(value);
					this.SendPropertyChanging();
					this._Comp = value;
					this.SendPropertyChanged("Comp");
					this.OnCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ent", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> Ent
		{
			get
			{
				return this._Ent;
			}
			set
			{
				if ((this._Ent != value))
				{
					this.OnEntChanging(value);
					this.SendPropertyChanging();
					this._Ent = value;
					this.SendPropertyChanged("Ent");
					this.OnEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorEnt", DbType="Decimal(19,8)")]
		public System.Nullable<decimal> PorEnt
		{
			get
			{
				return this._PorEnt;
			}
			set
			{
				if ((this._PorEnt != value))
				{
					this.OnPorEntChanging(value);
					this.SendPropertyChanging();
					this._PorEnt = value;
					this.SendPropertyChanged("PorEnt");
					this.OnPorEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="VarChar(8)")]
		public string Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Char(1)")]
		public System.Nullable<char> Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Prov", DbType="VarChar(6)")]
		public string Cod_Prov
		{
			get
			{
				return this._Cod_Prov;
			}
			set
			{
				if ((this._Cod_Prov != value))
				{
					this.OnCod_ProvChanging(value);
					this.SendPropertyChanging();
					this._Cod_Prov = value;
					this.SendPropertyChanged("Cod_Prov");
					this.OnCod_ProvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="VarChar(100)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this.OnProveedorChanging(value);
					this.SendPropertyChanging();
					this._Proveedor = value;
					this.SendPropertyChanged("Proveedor");
					this.OnProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VlrUnita", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VlrUnita
		{
			get
			{
				return this._VlrUnita;
			}
			set
			{
				if ((this._VlrUnita != value))
				{
					this.OnVlrUnitaChanging(value);
					this.SendPropertyChanging();
					this._VlrUnita = value;
					this.SendPropertyChanged("VlrUnita");
					this.OnVlrUnitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostEnt", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> CostEnt
		{
			get
			{
				return this._CostEnt;
			}
			set
			{
				if ((this._CostEnt != value))
				{
					this.OnCostEntChanging(value);
					this.SendPropertyChanging();
					this._CostEnt = value;
					this.SendPropertyChanged("CostEnt");
					this.OnCostEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFecha", DbType="Int")]
		public System.Nullable<int> IdFecha
		{
			get
			{
				return this._IdFecha;
			}
			set
			{
				if ((this._IdFecha != value))
				{
					this.OnIdFechaChanging(value);
					this.SendPropertyChanging();
					this._IdFecha = value;
					this.SendPropertyChanged("IdFecha");
					this.OnIdFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedidos")]
	public partial class Pedidos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _referencia1;
		
		private string _codcapi;
		
		private string _codunit;
		
		private string _codinsu;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _pedido;
		
		private System.Nullable<decimal> _ped;
		
		private System.Nullable<decimal> _aprob;
		
		private System.Nullable<decimal> _comp;
		
		private System.Nullable<decimal> _xgenorden;
		
		private string _orden;
		
		private string _usuario;
		
		private System.Nullable<int> _IdFecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onreferencia1Changing(string value);
    partial void Onreferencia1Changed();
    partial void OncodcapiChanging(string value);
    partial void OncodcapiChanged();
    partial void OncodunitChanging(string value);
    partial void OncodunitChanged();
    partial void OncodinsuChanging(string value);
    partial void OncodinsuChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnpedidoChanging(string value);
    partial void OnpedidoChanged();
    partial void OnpedChanging(System.Nullable<decimal> value);
    partial void OnpedChanged();
    partial void OnaprobChanging(System.Nullable<decimal> value);
    partial void OnaprobChanged();
    partial void OncompChanging(System.Nullable<decimal> value);
    partial void OncompChanged();
    partial void OnxgenordenChanging(System.Nullable<decimal> value);
    partial void OnxgenordenChanged();
    partial void OnordenChanging(string value);
    partial void OnordenChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnIdFechaChanging(System.Nullable<int> value);
    partial void OnIdFechaChanged();
    #endregion
		
		public Pedidos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia1", DbType="VarChar(20)")]
		public string referencia1
		{
			get
			{
				return this._referencia1;
			}
			set
			{
				if ((this._referencia1 != value))
				{
					this.Onreferencia1Changing(value);
					this.SendPropertyChanging();
					this._referencia1 = value;
					this.SendPropertyChanged("referencia1");
					this.Onreferencia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codcapi", DbType="VarChar(8)")]
		public string codcapi
		{
			get
			{
				return this._codcapi;
			}
			set
			{
				if ((this._codcapi != value))
				{
					this.OncodcapiChanging(value);
					this.SendPropertyChanging();
					this._codcapi = value;
					this.SendPropertyChanged("codcapi");
					this.OncodcapiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codunit", DbType="VarChar(8)")]
		public string codunit
		{
			get
			{
				return this._codunit;
			}
			set
			{
				if ((this._codunit != value))
				{
					this.OncodunitChanging(value);
					this.SendPropertyChanging();
					this._codunit = value;
					this.SendPropertyChanged("codunit");
					this.OncodunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codinsu", DbType="VarChar(8)")]
		public string codinsu
		{
			get
			{
				return this._codinsu;
			}
			set
			{
				if ((this._codinsu != value))
				{
					this.OncodinsuChanging(value);
					this.SendPropertyChanging();
					this._codinsu = value;
					this.SendPropertyChanged("codinsu");
					this.OncodinsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pedido", DbType="VarChar(8)")]
		public string pedido
		{
			get
			{
				return this._pedido;
			}
			set
			{
				if ((this._pedido != value))
				{
					this.OnpedidoChanging(value);
					this.SendPropertyChanging();
					this._pedido = value;
					this.SendPropertyChanged("pedido");
					this.OnpedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ped", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ped
		{
			get
			{
				return this._ped;
			}
			set
			{
				if ((this._ped != value))
				{
					this.OnpedChanging(value);
					this.SendPropertyChanging();
					this._ped = value;
					this.SendPropertyChanged("ped");
					this.OnpedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aprob", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> aprob
		{
			get
			{
				return this._aprob;
			}
			set
			{
				if ((this._aprob != value))
				{
					this.OnaprobChanging(value);
					this.SendPropertyChanging();
					this._aprob = value;
					this.SendPropertyChanged("aprob");
					this.OnaprobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> comp
		{
			get
			{
				return this._comp;
			}
			set
			{
				if ((this._comp != value))
				{
					this.OncompChanging(value);
					this.SendPropertyChanging();
					this._comp = value;
					this.SendPropertyChanged("comp");
					this.OncompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xgenorden", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> xgenorden
		{
			get
			{
				return this._xgenorden;
			}
			set
			{
				if ((this._xgenorden != value))
				{
					this.OnxgenordenChanging(value);
					this.SendPropertyChanging();
					this._xgenorden = value;
					this.SendPropertyChanged("xgenorden");
					this.OnxgenordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orden", DbType="VarChar(8)")]
		public string orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				if ((this._orden != value))
				{
					this.OnordenChanging(value);
					this.SendPropertyChanging();
					this._orden = value;
					this.SendPropertyChanged("orden");
					this.OnordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(8)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFecha", DbType="Int")]
		public System.Nullable<int> IdFecha
		{
			get
			{
				return this._IdFecha;
			}
			set
			{
				if ((this._IdFecha != value))
				{
					this.OnIdFechaChanging(value);
					this.SendPropertyChanging();
					this._IdFecha = value;
					this.SendPropertyChanged("IdFecha");
					this.OnIdFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
